---
- name: Ensure that source directories exist
  file: path="{{ item }}"
        owner="{{ ansible_ssh_user }}"
        group=mmw
        mode=0755
        state=directory
  with_items:
    - "/opt/geop"

- name: Clone application source
  git: repo=https://github.com/WikiWatershed/model-my-watershed.git
       dest=/opt/geop
       version="{{ deploy_branch }}"
