---
- name: Configure Nginx site
  template: src=nginx-app.conf.j2
            dest=/etc/nginx/sites-available/mmw-app.conf
  notify:
    - Restart Nginx

- name: Enable Nginx site
  file: src=/etc/nginx/sites-available/mmw-app.conf
        dest=/etc/nginx/sites-enabled/mmw-app
        state=link
  notify:
    - Restart Nginx
