---
- name: Create folders for static files
  file: path={{ item }}
        state=directory
        owner=root
        group=mmw
        mode=0775
  with_items:
    - "{{ app_static_root }}"
    - "{{ app_media_root }}"
    - "{{ app_static_cache }}"

- name: Install application JavaScript dependencies
  command: npm install --unsafe-perm
  args:
    chdir: "{{ app_home }}"

- name: Create static files and run collectstatic (staging/production)
  command: envdir {{ app_config_home }} ./bundle.sh
  args:
    chdir: "{{ app_home }}"
  when: "['development'] | is_not_in(group_names)"

- name: Create static files and run collectstatic (development)
  command: envdir {{ app_config_home }} ./bundle.sh --debug
  args:
    chdir: "{{ app_home }}"
  when: "['development'] | is_in(group_names)"

- name: Run Django collectstatic command
  command: envdir {{ app_config_home }} ./manage.py collectstatic --noinput
  args:
    chdir: "{{ app_home }}"

- name: Create JS test harness
  template: src=testem-harness.html.j2
            dest={{ app_static_root }}/test.html
  sudo_user: mmw
  when: "['development', 'test'] | some_are_in(group_names)"
