---
- name: Clone application source
  git: repo=https://github.com/WikiWatershed/model-my-watershed.git
       dest=/opt/model-my-watershed
       version="{{ app_deploy_branch }}"

- name: Ensure that app_home exists
  file: path="{{ app_home }}"
        owner="{{ ansible_ssh_user }}"
        group=mmw
        mode=0755
        state=directory

- name: Synchronize Django application into app_home
  synchronize: archive=no
               checksum=yes
               compress=no
               recursive=yes
               set_remote_user=no
               src=/opt/model-my-watershed/src/mmw/
               dest="{{ app_home }}/"
