---
- name: Create service account for Celery
  user: name=celery
        system=yes
        home=/var/lib/celery
        state=present

- name: Add Celery user to mmw group
  user: name=celery
        append=yes
        groups=mmw
        state=present
