---
- name: Install numba
  pip: name=numba version={{ numba_version }}

- name: Install numpy
  pip: name=numpy version={{ numpy_version }}

- name: Install application Python dependencies for development and test
  pip: requirements="{{ app_home }}/requirements/{{ item }}.txt"
  with_items:
    - development
    - test
  when: "['development', 'test'] | some_are_in(group_names)"
  notify:
    - Restart Celery

- name: Install application Python dependencies for production
  pip: requirements="{{ app_home }}/requirements/production.txt"
  when: "['packer'] | is_in(group_names)"
  notify:
    - Restart Celery
