---
- name: Touch log file if it does not exist
  copy: content="" dest="{{ tiler_log }}" force=no

- name: Set log file permissions
  file: path={{ tiler_log }} owner=mmw group=mmw mode=0644

- name: Configure Tiler log rotation
  template: src=logrotate-mmw-tiler.j2 dest=/etc/logrotate.d/mmw-tiler
